---
- hosts: all
  become: yes
  vars: 
  - ansible_python_interpreter: /usr/bin/python
  tasks:
  - name: Non-Zero return
    shell: “ls | grep wp-config.php”
    ignore_errors: true

  - name: install httpd
    yum:
      name: httpd
      state: latest
  - name: start httpd
    service:
      name: httpd
      state: started
  - name: Enable service httpd, and not touch the state
    service:
      name: httpd
      enabled: yes
  - name: copy file from source to destination
    copy:
      src: index.html
      dest: /var/www/html/
